# Generated by Django 3.2.9 on 2022-01-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_photos_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
