# Generated by Django 4.0.1 on 2022-01-23 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnote', '0002_alter_note_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('dislike', models.IntegerField(blank=True, null=True)),
                ('noteId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnote.note')),
            ],
        ),
    ]
