# Generated by Django 4.0.1 on 2022-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnote', '0003_totallikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='totalLikes',
        ),
    ]
